// Playwright config (generated by qa-kit init --preset web-e2e).
// Emitted into qa-e2e/; paths are interpreted relative to this file.
//
// Artifact layout (all under project-root qa-results/, gitignored):
//   ../qa-results/e2e/test-artifacts/      per-test traces / videos / .last-run.json (outputDir)
//   ../qa-results/e2e/playwright-html/     html reporter
//   ../qa-results/e2e/playwright-report.json  json reporter (qa-kit summary 的数据源)
//   ../qa-results/e2e/allure-results/      allure raw（需 `pnpm add -D allure-playwright`）
//   ../qa-results/e2e/allure-report/       allure generate 后的 HTML
//   ../qa-results/e2e/blob-reports/        blob reporter (shard merge 载体)
//
// Browser：默认系统 Chrome（channel: 'chrome'），首次运行前注册一次：
//   pnpm exec playwright install chrome ffmpeg
// 若本机未装 Chrome，上面命令会自动下载稳定版；Chrome 已装则只注册标记。
//
// Headed / headless：
//   默认 headless（CI 同款）。本机想每次都开窗口：在 .env 里设 QA_E2E_HEADED=1
//   即可。CLI 标志 `--headed` / `--ui` / `--debug` 永远覆盖此默认。
//
// 人工登录（出金等用例）：
//   `WithdrawPage.goto` 会先打开 QA_LOGIN_ENTRY_PATH（默认 /login），在登录页等待最多
//   QA_MANUAL_LOGIN_TIMEOUT_MS（默认 300s）直至离开登录页，再进入出入金页继续脚本。
//   请 headed 运行；CI 默认会失败除非 QA_ALLOW_MANUAL_LOGIN_IN_CI=1（或改用 storageState 免人工）。
//
// Allure HTML 导出（qa-e2e/ 里跑）：
//   npx allure generate ../qa-results/e2e/allure-results --clean -o ../qa-results/e2e/allure-report
//   npx allure open ../qa-results/e2e/allure-report
//
// CI shard merge (blob → html):
//   pnpm exec playwright merge-reports --reporter=html ../qa-results/e2e/blob-reports

import { defineConfig } from '@playwright/test';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

import { loadProjectEnvFiles, resolveApiBaseUrl, resolveBaseUrl } from './lib/env/index.ts';

/** 加载根 `.env` + `env/.env.<QA_ENV>`（Test3 / Testnet / Prd）。 */
loadProjectEnvFiles({ rootDir: resolve(dirname(fileURLToPath(import.meta.url)), '..') });

// Sanity check：缺 qa-kit 时给人话报错，避免 Playwright 栈里报"ERR_MODULE_NOT_FOUND"
// 让人摸不着头脑（实际原因只是忘了 pnpm install）。
let createWebPlaywrightConfig: typeof import('@zmx/qa-kit/runners/web').createWebPlaywrightConfig;
try {
  ({ createWebPlaywrightConfig } = await import('@zmx/qa-kit/runners/web'));
} catch {
  console.error(
    '[qa-kit] @zmx/qa-kit 未安装或解析不到；先跑：pnpm install\n' +
      '  （未装的话 Playwright 会用自己的默认产物路径，test-results/ 会漏到项目根）',
  );
  process.exit(1);
}

const baseURL = resolveBaseUrl();
const apiBaseURL = resolveApiBaseUrl();
const headed = process.env['QA_E2E_HEADED'] === '1';

const apiDefaultHeaders: Record<string, string> = {
  Accept: 'application/json',
  'Content-Type': 'application/json',
};

// Auth:
// - 默认 authMode: 'none' —— demo spec 不需要登录态，一跑即过。
// - 需要登录时改成 'storage-state' 并跑 `tests/setup/auth.setup.ts` 生成
//   ../.qa-kit/auth/user.json；或在单条 test 里显式
//   `test.use({ storageState: '../.qa-kit/auth/other.json' })`。
const webRunner = createWebPlaywrightConfig({
  baseURL,
  testDir: 'tests',
  authMode: 'storage-state',
  // 与 `tests/setup/auth.setup.ts` 落盘路径一致（相对本文件所在目录 qa-e2e/）
  storageStatePath: '../.qa-kit/auth/user-0.json',
  browsers: ['chromium'],
  channel: 'chrome',
  headed,
  // reporter / outputDir 使用 qa-kit 默认值（qa-results/e2e/*）；见顶部注释。
  allure: {},
  blobReporter: {},
});

const apiSpecIgnore = ['**/*.api.spec.ts'];

export default defineConfig({
  ...webRunner,
  timeout: 30_000,
  expect: { timeout: 5_000 },
  projects: [
    ...webRunner.projects.map((project) => ({
      ...project,
      testIgnore: [...(webRunner.testIgnore ?? []), ...apiSpecIgnore],
    })),
    {
      name: 'api',
      testMatch: /.*\.api\.spec\.ts$/,
      testIgnore: [...(webRunner.testIgnore ?? [])],
      use: {
        baseURL: apiBaseURL,
        extraHTTPHeaders: apiDefaultHeaders,
        // 不继承 UI 的 storageState 文件（纯 HTTP request，走 QA_API_TOKEN）
        storageState: { cookies: [], origins: [] },
      },
    },
  ],
});
