#!/usr/bin/env node
/**
 * Validate OpenAPI specs under contracts/openapi/, bundle, emit types + thin clients.
 */
import { mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import SwaggerParser from '@apidevtools/swagger-parser';

const execFileAsync = promisify(execFile);
const __dirname = dirname(fileURLToPath(import.meta.url));
const ROOT = join(__dirname, '..');
const CONTRACTS_DIR = join(ROOT, 'contracts', 'openapi');
const OUT_DIR = join(ROOT, 'qa-e2e', 'lib', 'api', 'generated');

const OPENAPI_EXT = /\.(ya?ml|json)$/i;

function serviceNameFromFile(file: string): string {
  return basename(file)
    .replace(/\.openapi\.(json|ya?ml)$/i, '')
    .replace(OPENAPI_EXT, '');
}

function toPascalCase(slug: string): string {
  return slug
    .split(/[-_]+/)
    .filter(Boolean)
    .map((p) => p.charAt(0).toUpperCase() + p.slice(1))
    .join('');
}

async function listSpecFiles(): Promise<string[]> {
  const entries = await readdir(CONTRACTS_DIR, { withFileTypes: true });
  return entries
    .filter((e) => e.isFile() && OPENAPI_EXT.test(e.name))
    .map((e) => join(CONTRACTS_DIR, e.name))
    .sort();
}

function clientSource(service: string, pascal: string): string {
  return `/**
 * Auto-generated by \`pnpm openapi:sync\`. Do not edit manually.
 */
import createClient from 'openapi-fetch';
import type { paths } from './${service}.d.ts';

export type ${pascal}Paths = paths;

export function create${pascal}Client(options: {
  baseUrl: string;
  headers?: Record<string, string>;
}) {
  return createClient<paths>({
    baseUrl: options.baseUrl.replace(/\\/$/, ''),
    headers: options.headers,
  });
}
`;
}

async function runOpenapiTypescript(inputPath: string, dtsPath: string): Promise<void> {
  const bin = join(ROOT, 'node_modules', '.bin', 'openapi-typescript');
  await execFileAsync(bin, [inputPath, '-o', dtsPath], { cwd: ROOT });
}

async function syncOne(specPath: string): Promise<void> {
  const service = serviceNameFromFile(specPath);
  const pascal = toPascalCase(service);
  console.log(`[openapi:sync] ${service} …`);

  const bundled = await SwaggerParser.bundle(specPath);
  await SwaggerParser.validate(bundled);

  await mkdir(OUT_DIR, { recursive: true });

  const bundledPath = join(OUT_DIR, `${service}.bundled.json`);
  const dtsPath = join(OUT_DIR, `${service}.d.ts`);
  const clientPath = join(OUT_DIR, `${service}-client.ts`);

  await writeFile(bundledPath, JSON.stringify(bundled, null, 2), 'utf8');
  await runOpenapiTypescript(specPath, dtsPath);
  await writeFile(clientPath, clientSource(service, pascal), 'utf8');

  console.log(`  → ${bundledPath}`);
  console.log(`  → ${dtsPath}`);
  console.log(`  → ${clientPath}`);
}

async function writeIndex(services: string[]): Promise<void> {
  const lines = services.map((s) => {
    const pascal = toPascalCase(s);
    return `export { create${pascal}Client, type ${pascal}Paths } from './${s}-client.ts';`;
  });
  await writeFile(join(OUT_DIR, 'index.ts'), `${lines.join('\n')}\n`, 'utf8');
}

async function main(): Promise<void> {
  const specs = await listSpecFiles();
  if (specs.length === 0) {
    console.error(`[openapi:sync] No specs in ${CONTRACTS_DIR}`);
    process.exit(2);
  }

  for (const spec of specs) {
    await syncOne(spec);
  }
  await writeIndex(specs.map(serviceNameFromFile));

  const readme = await readFile(join(CONTRACTS_DIR, 'README.md'), 'utf8').catch(() => '');
  if (!readme) {
    console.warn('[openapi:sync] contracts/openapi/README.md missing (optional)');
  }

  console.log('[openapi:sync] done.');
}

main().catch((err) => {
  console.error('[openapi:sync] failed:', err);
  process.exit(2);
});
